name: Import safety canary

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: false  # Disable LFS

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install kfp and docker
      run: |
        python -m pip install kfp
        pip install docker

    - name: Install minimal dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Install commons itself
      run: |
        pip install .

    - name: Build with minimal dependencies
      run: |
        kfp component build . --component-filepattern catalogue/model_loaders/no_model.py --no-push-image
